version: '3.3'

services:
  dev-portal:
    image: moesif/dev-portal
    ports:
      - 4000:4000
    environment:
      - HOST=127.0.0.1
      - PORT=4000
      - REACT_APP_DEV_PORTAL_API_SERVER=http://127.0.0.1:3030
      - REACT_APP_AUTH_PROVIDER=Auth0
      - REACT_APP_AUTH0_DOMAIN=
      - REACT_APP_AUTH0_CLIENT_ID=
      - REACT_APP_STRIPE_PUBLISHABLE_KEY=
      - REACT_APP_STRIPE_MANAGEMENT_URL=

  dev-portal-api:
    image: moesif/dev-portal-api
    ports:
      - 3030:3030
    environment:
      - FRONT_END_DOMAIN=127.0.0.1:4000
      - MOESIF_APPLICATION_ID=
      - MOESIF_MANAGEMENT_TOKEN=
      - MOESIF_TEMPLATE_WORKSPACE_ID_LIVE_EVENT_LOG=
      - MOESIF_TEMPLATE_WORKSPACE_ID_TIME_SERIES=
      - STRIPE_API_KEY=
      - AUTH_PROVIDER=Auth0
      - AUTH0_DOMAIN=
      - PLUGIN_APIM_PROVIDER=Kong
      - PLUGIN_KONG_URL=https://us.api.konghq.com/v2/control-planes/{your-control-plane-id}/core-entities
      - PLUGIN_KONNECT_API_URL=https://us.api.konghq.com
      - PLUGIN_KONNECT_API_VERSION=v2
      - PLUGIN_KONNECT_RUNTIME_GROUP_NAME=
      - PLUGIN_KONNECT_PAT=